# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: intel-infra-provider-crds
description: Custom Resource Definitions for Intel Cluster API Provider
type: application
version: 1.2.8-dev
annotations:
  revision: b904bf76fb8fdb85d3c61486ad395d25ca57d414
  created: "2025-11-10T18:36:49Z"
appVersion: 1.2.8-dev
