# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: intel-infra-provider-crds
description: Custom Resource Definitions for Intel Cluster API Provider
type: application
version: 1.2.7-dev-a2ca4714
annotations:
  revision: a2ca47144e36e33c602bd99927d55885d968b9f7
  created: "2025-11-05T21:44:54Z"
appVersion: 1.2.7-dev-a2ca4714
