apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: IntelMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-intel
    app.kubernetes.io/managed-by: kustomize
  name: intelmachinetemplate-sample
spec:
  template:
    spec: {}
