apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: IntelMachine
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-intel
    app.kubernetes.io/managed-by: kustomize
  name: intelmachine-sample
spec:
  hostID: 12345678-1234-1234-1234-123456789012
  providerID: sample-provider-id
