apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: IntelMachineBinding
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-intel
    app.kubernetes.io/managed-by: kustomize
  name: intelmachinebinding-sample
spec:
  clusterName: intelcluster-sample
  intelMachineTemplateName: intelmachinetemplate-sample
  hostID: 12345678-1234-1234-1234-123456789012
