# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: intel-infra-provider
description: The Intel Cluster API Provider
type: application
version: 1.3.1
annotations:
  revision: 45825ac8d246455282c07fef4b1943d0828615a5
  created: "2025-11-25T04:50:31Z"
appVersion: 1.3.1
