# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: intel-infra-provider
description: The Intel Cluster API Provider
type: application
version: 1.2.7-dev-5e5dc15a
annotations:
  revision: 5e5dc15a065c6213bfe55865f2fe0039a2a9ec18
  created: "2025-11-04T23:55:07Z"
appVersion: 1.2.7-dev-5e5dc15a
