# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: intel-infra-provider
description: The Intel Cluster API Provider
type: application
version: 1.2.5
annotations:
  revision: 965ca6dd128374ab55665fe3871bebf6a781088b
  created: "2025-10-28T08:53:13Z"
appVersion: 1.2.5
